# Generated by Django 5.0.6 on 2024-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_rename_price_room_basefare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='numOfGuest',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
