# Generated by Django 5.0.6 on 2024-05-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_booking_numofguest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='room',
            name='roomSize',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('King', 'King')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_fare',
            field=models.FloatField(default=0.0),
        ),
    ]
